server {
    listen 80;
    root /usr/share/nginx/html;
    gzip on;

    location /api/ {
        proxy_pass http://api:8000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Connection "";
        proxy_set_header X-Accel-Buffering no;
        proxy_buffering off;
        proxy_cache off;
        gzip off;
        proxy_read_timeout 300s;
    }

    location / {
        try_files $uri /index.html;
    }
}
