# Allow-listed WWI tables, parents first. (mssql_schema, mssql_table, pg_schema, pg_table)
TABLES = [
    ("Application", "Countries", "application", "countries"),
    ("Application", "StateProvinces", "application", "state_provinces"),
    ("Application", "Cities", "application", "cities"),
    ("Application", "DeliveryMethods", "application", "delivery_methods"),
    ("Application", "PaymentMethods", "application", "payment_methods"),
    ("Application", "TransactionTypes", "application", "transaction_types"),
    ("Application", "People", "application", "people"),
    ("Sales", "CustomerCategories", "sales", "customer_categories"),
    ("Sales", "BuyingGroups", "sales", "buying_groups"),
    ("Purchasing", "SupplierCategories", "purchasing", "supplier_categories"),
    ("Purchasing", "Suppliers", "purchasing", "suppliers"),
    ("Warehouse", "Colors", "warehouse", "colors"),
    ("Warehouse", "PackageTypes", "warehouse", "package_types"),
    ("Warehouse", "StockGroups", "warehouse", "stock_groups"),
    ("Warehouse", "StockItems", "warehouse", "stock_items"),
    ("Warehouse", "StockItemHoldings", "warehouse", "stock_item_holdings"),
    ("Warehouse", "StockItemStockGroups", "warehouse", "stock_item_stock_groups"),
    ("Sales", "Customers", "sales", "customers"),
    ("Sales", "Orders", "sales", "orders"),
    ("Sales", "Invoices", "sales", "invoices"),
    ("Purchasing", "PurchaseOrders", "purchasing", "purchase_orders"),
    ("Sales", "OrderLines", "sales", "order_lines"),
    ("Sales", "InvoiceLines", "sales", "invoice_lines"),
    ("Purchasing", "PurchaseOrderLines", "purchasing", "purchase_order_lines"),
    ("Warehouse", "StockItemTransactions", "warehouse", "stock_item_transactions"),
    ("Sales", "CustomerTransactions", "sales", "customer_transactions"),
    ("Purchasing", "SupplierTransactions", "purchasing", "supplier_transactions"),
]

SKIP_TYPE_NAMES = {
    "geography",
    "geometry",
    "hierarchyid",
    "varbinary",
    "binary",
    "image",
    "xml",
    "sysname",
}

SKIP_COLUMN_NAMES = {
    "Photo",
    "HashedPassword",
    "UserPreferences",
    "CustomFields",
    "OtherLanguages",
    "Tags",
    "SearchDetails",
    "InternalComments",
    "PhotoUrl",
    "ValidFrom",
    "ValidTo",
    "DeliveryLocation",
    "Border",
}

INDEXES = [
    "CREATE INDEX IF NOT EXISTS orders_order_date_idx ON sales.orders (order_date)",
    "CREATE INDEX IF NOT EXISTS orders_customer_id_idx ON sales.orders (customer_id)",
    "CREATE INDEX IF NOT EXISTS order_lines_order_id_idx ON sales.order_lines (order_id)",
    "CREATE INDEX IF NOT EXISTS order_lines_stock_item_id_idx ON sales.order_lines (stock_item_id)",
    "CREATE INDEX IF NOT EXISTS invoices_invoice_date_idx ON sales.invoices (invoice_date)",
    "CREATE INDEX IF NOT EXISTS invoices_customer_id_idx ON sales.invoices (customer_id)",
    "CREATE INDEX IF NOT EXISTS invoice_lines_invoice_id_idx ON sales.invoice_lines (invoice_id)",
    "CREATE INDEX IF NOT EXISTS invoice_lines_stock_item_id_idx ON sales.invoice_lines (stock_item_id)",
    "CREATE INDEX IF NOT EXISTS customers_delivery_city_id_idx ON sales.customers (delivery_city_id)",
    "CREATE INDEX IF NOT EXISTS po_order_date_idx ON purchasing.purchase_orders (order_date)",
    "CREATE INDEX IF NOT EXISTS po_expected_delivery_idx ON purchasing.purchase_orders (expected_delivery_date)",
    "CREATE INDEX IF NOT EXISTS po_supplier_id_idx ON purchasing.purchase_orders (supplier_id)",
    "CREATE INDEX IF NOT EXISTS pol_po_id_idx ON purchasing.purchase_order_lines (purchase_order_id)",
    "CREATE INDEX IF NOT EXISTS pol_stock_item_id_idx ON purchasing.purchase_order_lines (stock_item_id)",
    "CREATE INDEX IF NOT EXISTS sit_item_when_idx ON warehouse.stock_item_transactions (stock_item_id, transaction_occurred_when)",
    "CREATE INDEX IF NOT EXISTS cities_state_province_id_idx ON application.cities (state_province_id)",
]
